GET http://localhost:3003/api/blogs
### 
POST http://localhost:3003/api/blogs  HTTP/1.1
Content-Type: application/json

{
    "title": "spring break",
    "author": "aa",
    "url": "",
    "likes": 7
}

###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users  HTTP/1.1
Content-Type: application/json

{
    "username": "biesan",
    "name": "name bdd",
    "password": "aaa",
}

###
POST http://localhost:3003/api/users  HTTP/1.1
Content-Type: application/json

{
    "username": "spring break",
    "name": "aa",
    "password": "dddddddddddd"
}